version: '3'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    volumes:
      - .:/usr/src/app
    depends_on:
      - app

  app:
    build:
      context: ./node
    container_name: app
    entrypoint: wait-for db:3306 -t 40 -- node index.js
    networks:
      - node-network
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge